[package]
name = "sui-sf-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backoff = { version = "0.4", features = ["futures", "futures-core", "pin-project-lite", "tokio", "tokio_1"] }
eyre = "0.6.8"
env_logger = "0.10.0"
clap = { version = "4.2.7", features = ["derive"] }
futures = "0.3.23"
jsonrpsee = { version = "0.16.2", features = ["full"] }
log = "0.4.17"
sui-json-rpc = { git = "https://github.com/MystenLabs/sui", rev = "f8f63d20c4" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", rev = "f8f63d20c4" }
sui-indexer = { git = "https://github.com/MystenLabs/sui", rev = "f8f63d20c4" }
sui-types = { git = "https://github.com/MystenLabs/sui", rev = "f8f63d20c4" }
tokio = { version = "1.27.0", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.9.2", features = ["prost"] }
